USE [master]
GO
/****** Object:  Database [GTIERP]    Script Date: 02/03/2014 14:03:34 ******/
CREATE DATABASE [GTIERP] ON  PRIMARY 
( NAME = N'GTIERP', FILENAME = N'd:\Program Files\Microsoft SQL Server\MSSQL10_50.GTIDB\MSSQL\DATA\GTIERP.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GTIERP_log', FILENAME = N'd:\Program Files\Microsoft SQL Server\MSSQL10_50.GTIDB\MSSQL\DATA\GTIERP_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [GTIERP] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GTIERP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GTIERP] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [GTIERP] SET ANSI_NULLS OFF
GO
ALTER DATABASE [GTIERP] SET ANSI_PADDING OFF
GO
ALTER DATABASE [GTIERP] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [GTIERP] SET ARITHABORT OFF
GO
ALTER DATABASE [GTIERP] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [GTIERP] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [GTIERP] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [GTIERP] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [GTIERP] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [GTIERP] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [GTIERP] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [GTIERP] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [GTIERP] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [GTIERP] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [GTIERP] SET  DISABLE_BROKER
GO
ALTER DATABASE [GTIERP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [GTIERP] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [GTIERP] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [GTIERP] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [GTIERP] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [GTIERP] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [GTIERP] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [GTIERP] SET  READ_WRITE
GO
ALTER DATABASE [GTIERP] SET RECOVERY FULL
GO
ALTER DATABASE [GTIERP] SET  MULTI_USER
GO
ALTER DATABASE [GTIERP] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [GTIERP] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'GTIERP', N'ON'
GO
USE [GTIERP]
GO
/****** Object:  User [AppUser]    Script Date: 02/03/2014 14:03:34 ******/
CREATE USER [AppUser] FOR LOGIN [AppUser] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[EMPLOYEES]    Script Date: 02/03/2014 14:03:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EMPLOYEES](
	[EMPLOYEEID] [bigint] IDENTITY(1,1) NOT NULL,
	[FNAME] [varchar](30) NULL,
	[LNAME] [varchar](50) NULL,
	[ADDRESS] [varchar](200) NULL,
	[BIRTHDATE] [datetime] NULL,
	[HIREDATE] [datetime] NULL,
	[GENDER] [char](1) NULL,
	[GRADUATION] [varchar](100) NULL,
	[HOMEPHONE] [varchar](16) NULL,
	[MOBILEPHONE] [varchar](16) NULL,
	[MARRIED] [char](1) NULL,
	[SOCIALINSURANCE] [bigint] NULL,
	[TCID] [varchar](11) NULL,
	[AUTHORIZATIONID] [bigint] NULL,
	[USERNAME] [varchar](30) NULL,
	[PASWORD] [varchar](30) NULL,
	[ISACTIVE] [char](1) NULL,
	[DEPARTMENTPOZITIONID] [bigint] NULL,
	[BRANCHDEPARTMENTID] [bigint] NULL,
	[ISHANDICAPPED] [char](1) NULL,
	[HANDICAP] [varchar](100) NULL,
	[ISILL] [char](1) NULL,
	[ILLNESS] [varchar](100) NULL,
	[MILITARYSITUATION] [char](1) NULL,
	[DELAYDATE] [datetime] NULL,
	[EMAIL] [varchar](100) NULL,
	[TITLE] [varchar](100) NULL,
	[REGISTERNUMBER] [varchar](30) NULL,
	[PHOTO] [varchar](200) NULL,
	[EXPLANATION] [varchar](200) NULL,
	[BLOODID] [bigint] NULL,
	[FIREDATE] [datetime] NULL,
	[UNVANID] [bigint] NULL,
	[EXEMPLOYEEID] [bigint] NULL,
	[BIRTHPLACE] [varchar](200) NULL,
	[SGKSICILNO] [varchar](200) NULL,
	[IMZAYETKILISIMI] [numeric](38, 0) NULL,
	[GIRISSIRANO] [bigint] NULL,
	[MAILBRANCHDEPARTMANID] [bigint] NULL,
	[IBAN] [varchar](50) NULL,
	[KALANIZINGUN] [int] NULL,
	[KALANIZINSAAT] [nvarchar](50) NULL,
	[IZINATAMATARIH] [datetime] NULL,
 CONSTRAINT [PK_EMPLOYEES] PRIMARY KEY CLUSTERED 
(
	[EMPLOYEEID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
